import type { GuiAgentTask } from "./projectTypes.js";

export const guiAgentTasks: GuiAgentTask[] = [
  {
    taskId: "support-order-refund-policy",
    title: "Find refund policy for an order",
    domain: "Customer support portal",
    instruction: "Open order R-1842 and find the refund policy note, not the shipping policy note.",
    startUrl: "https://demo.local/support",
    successCriteria: "Order R-1842 is open and the refund policy note is selected.",
    riskTags: ["shared prefix", "late divergence", "model comparison"],
    textState:
      "Support portal with a global search field, order result R-1842, and separate tabs for Refund policy, Shipping policy, and Timeline.",
    visualState:
      "The order page has visually similar policy tabs; Refund policy and Shipping policy appear side by side after the same search flow.",
    screenshotSize: { width: 1280, height: 820 },
    traces: [
      {
        traceId: "support-order-refund-gpt4",
        agentId: "gpt4-0613-cot",
        agentKind: "offline_run",
        modelId: "GPT4-0613 + CoT",
        taskId: "support-order-refund-policy",
        steps: [
          {
            stepIndex: 1,
            observationType: "mixed",
            observationSummary: "Support home shows a search field for order id or customer email.",
            actionType: "type",
            target: { label: "Search orders", domSelector: "#support-search", bbox: [326, 184, 420, 42] },
            inputText: "R-1842",
            structuredRationale: "Search for order R-1842 to open the relevant support record.",
            confidence: 0.9,
            stateAfter: "search_query_entered",
            url: "https://demo.local/support",
          },
          {
            stepIndex: 2,
            observationType: "mixed",
            observationSummary: "Search results list order R-1842 with a detail link.",
            actionType: "click",
            target: { label: "Order R-1842", domSelector: "#order-r-1842", bbox: [316, 288, 238, 44] },
            structuredRationale: "Open order R-1842 before selecting the requested policy note.",
            confidence: 0.9,
            stateAfter: "order_detail_open",
            url: "https://demo.local/support/orders/R-1842",
          },
          {
            stepIndex: 3,
            observationType: "mixed",
            observationSummary: "Order detail shows adjacent tabs for Refund policy and Shipping policy.",
            actionType: "click",
            target: { label: "Refund policy", domSelector: "#tab-refund-policy", bbox: [410, 352, 158, 38] },
            structuredRationale: "The instruction asks for the refund policy note, so the refund tab is selected.",
            confidence: 0.88,
            stateAfter: "refund_policy_tab_open",
            url: "https://demo.local/support/orders/R-1842?tab=refund",
          },
          {
            stepIndex: 4,
            observationType: "mixed",
            observationSummary: "Refund policy note is visible on the same order detail page.",
            actionType: "click",
            target: { label: "Refund policy note", domSelector: "#refund-note", bbox: [438, 492, 360, 48] },
            structuredRationale: "Selecting the visible refund note completes the requested lookup.",
            confidence: 0.86,
            stateAfter: "refund_policy_note_selected",
            url: "https://demo.local/support/orders/R-1842?tab=refund",
          },
        ],
      },
      {
        traceId: "support-order-refund-gpt35",
        agentId: "gpt35-turbo-direct",
        agentKind: "offline_run",
        modelId: "GPT3.5-turbo + Direct",
        taskId: "support-order-refund-policy",
        steps: [
          {
            stepIndex: 1,
            observationType: "mixed",
            observationSummary: "Support home shows a search field for order id or customer email.",
            actionType: "type",
            target: { label: "Search orders", domSelector: "#support-search", bbox: [326, 184, 420, 42] },
            inputText: "R-1842",
            structuredRationale: "Search for order R-1842 to open the relevant support record.",
            confidence: 0.9,
            stateAfter: "search_query_entered",
            url: "https://demo.local/support",
          },
          {
            stepIndex: 2,
            observationType: "mixed",
            observationSummary: "Search results list order R-1842 with a detail link.",
            actionType: "click",
            target: { label: "Order R-1842", domSelector: "#order-r-1842", bbox: [316, 288, 238, 44] },
            structuredRationale: "Open order R-1842 before selecting the requested policy note.",
            confidence: 0.9,
            stateAfter: "order_detail_open",
            url: "https://demo.local/support/orders/R-1842",
          },
          {
            stepIndex: 3,
            observationType: "mixed",
            observationSummary: "Order detail shows adjacent tabs for Refund policy and Shipping policy.",
            actionType: "click",
            target: { label: "Shipping policy", domSelector: "#tab-shipping-policy", bbox: [574, 352, 164, 38] },
            structuredRationale: "The visible policy tabs are similar, and shipping policy is selected as the likely policy note.",
            confidence: 0.72,
            stateAfter: "shipping_policy_tab_open",
            url: "https://demo.local/support/orders/R-1842?tab=shipping",
          },
          {
            stepIndex: 4,
            observationType: "mixed",
            observationSummary: "The page still shows order R-1842, but the shipping policy note is selected.",
            actionType: "click",
            target: { label: "Shipping policy note", domSelector: "#shipping-note", bbox: [438, 492, 372, 48] },
            structuredRationale: "Selecting the visible shipping note follows the currently active policy tab.",
            confidence: 0.68,
            stateAfter: "shipping_policy_note_selected",
            url: "https://demo.local/support/orders/R-1842?tab=shipping",
          },
        ],
      },
    ],
  },
  {
    taskId: "settings-notifications",
    title: "Disable promotional notifications",
    domain: "Account settings",
    instruction: "Open notification settings and turn off promotional emails while keeping security alerts enabled.",
    startUrl: "https://demo.local/settings",
    successCriteria: "Promotional emails disabled; security alerts still enabled.",
    riskTags: ["ambiguous labels", "settings form", "rejoin expected"],
    textState:
      "Settings page with sidebar links: Profile, Security, Notifications, Billing. Notification form includes Security alerts and Promotional emails toggles.",
    visualState:
      "White settings UI. The Notifications sidebar item is visually subtle; the promotional toggle is lower in the form than the security toggle.",
    screenshotSize: { width: 1280, height: 820 },
    traces: [
      {
        traceId: "settings-notifications-text",
        agentId: "text-dom-agent",
        agentKind: "text_dom",
        modelId: "gui-text-agent",
        taskId: "settings-notifications",
        steps: [
          {
            stepIndex: 1,
            observationType: "dom",
            observationSummary: "DOM exposes a Notifications sidebar link.",
            actionType: "click",
            target: { label: "Notifications", domSelector: "#nav-notifications", bbox: [48, 266, 172, 36] },
            structuredRationale: "The instruction asks for notification settings, so the sidebar link is the direct route.",
            confidence: 0.91,
            stateAfter: "notifications_panel_open",
          },
          {
            stepIndex: 2,
            observationType: "dom",
            observationSummary: "Form contains two toggles: Security alerts and Promotional emails.",
            actionType: "click",
            target: { label: "Promotional emails toggle", domSelector: "#promo-email-toggle", bbox: [904, 512, 52, 28] },
            structuredRationale: "Promotional emails are the target to disable; security alerts should be left untouched.",
            confidence: 0.87,
            stateAfter: "promo_disabled",
          },
          {
            stepIndex: 3,
            observationType: "dom",
            observationSummary: "Save button is enabled after the promotional toggle changes.",
            actionType: "click",
            target: { label: "Save changes", domSelector: "#save-notifications", bbox: [810, 666, 146, 40] },
            structuredRationale: "Saving commits the notification preference change.",
            confidence: 0.86,
            stateAfter: "settings_saved",
          },
        ],
      },
      {
        traceId: "settings-notifications-vision",
        agentId: "vision-gui-agent",
        agentKind: "vision_gui",
        modelId: "gui-vision-agent",
        taskId: "settings-notifications",
        steps: [
          {
            stepIndex: 1,
            observationType: "screenshot",
            observationSummary: "Screenshot shows a prominent Security card and a subtler Notifications link in the sidebar.",
            actionType: "click",
            target: { label: "Security", domSelector: "#nav-security", bbox: [48, 218, 172, 36] },
            structuredRationale: "The visible Security section appears related to alerts and account protection.",
            confidence: 0.74,
            stateAfter: "security_panel_open",
          },
          {
            stepIndex: 2,
            observationType: "mixed",
            observationSummary: "Security panel does not contain promotional email controls; sidebar remains visible.",
            actionType: "click",
            target: { label: "Notifications", domSelector: "#nav-notifications", bbox: [48, 266, 172, 36] },
            structuredRationale: "The current panel lacks the requested email controls, so the Notifications link is the better target.",
            confidence: 0.82,
            stateAfter: "notifications_panel_open",
          },
          {
            stepIndex: 3,
            observationType: "screenshot",
            observationSummary: "Promotional emails toggle is visible and currently enabled.",
            actionType: "click",
            target: { label: "Promotional emails toggle", domSelector: "#promo-email-toggle", bbox: [904, 512, 52, 28] },
            structuredRationale: "This toggle matches the promotional email instruction while security alerts stay unchanged.",
            confidence: 0.86,
            stateAfter: "promo_disabled",
          },
          {
            stepIndex: 4,
            observationType: "mixed",
            observationSummary: "Save button is enabled after the toggle change.",
            actionType: "click",
            target: { label: "Save changes", domSelector: "#save-notifications", bbox: [810, 666, 146, 40] },
            structuredRationale: "Saving commits the completed notification update.",
            confidence: 0.85,
            stateAfter: "settings_saved",
          },
        ],
      },
    ],
  },
  {
    taskId: "checkout-address",
    title: "Update shipping address",
    domain: "Checkout",
    instruction: "Change the shipping address, not the billing address, before continuing checkout.",
    startUrl: "https://demo.local/checkout",
    successCriteria: "Shipping address form opened and edited; billing address left unchanged.",
    riskTags: ["similar controls", "visual prominence", "persistent divergence"],
    textState:
      "Checkout page with sections for Shipping address and Billing address. Each section has an Edit button with accessible labels.",
    visualState:
      "The billing address card is visually higher contrast because it contains a warning badge, while shipping address appears above it.",
    screenshotSize: { width: 1280, height: 820 },
    traces: [
      {
        traceId: "checkout-address-text",
        agentId: "text-dom-agent",
        agentKind: "text_dom",
        modelId: "gui-text-agent",
        taskId: "checkout-address",
        steps: [
          {
            stepIndex: 1,
            observationType: "dom",
            observationSummary: "DOM labels separate Edit shipping address from Edit billing address.",
            actionType: "click",
            target: { label: "Edit shipping address", domSelector: "#edit-shipping", bbox: [824, 286, 156, 38] },
            structuredRationale: "The instruction explicitly asks to change shipping, so the shipping edit control is the target.",
            confidence: 0.93,
            stateAfter: "shipping_form_open",
          },
          {
            stepIndex: 2,
            observationType: "dom",
            observationSummary: "Shipping address form contains address line field.",
            actionType: "type",
            target: { label: "Shipping address line 1", domSelector: "#shipping-line1", bbox: [420, 386, 420, 40] },
            inputText: "145 Market Street",
            structuredRationale: "Typing into the shipping field changes the requested address.",
            confidence: 0.89,
            stateAfter: "shipping_address_edited",
          },
          {
            stepIndex: 3,
            observationType: "dom",
            observationSummary: "Continue button is enabled after the shipping form update.",
            actionType: "click",
            target: { label: "Continue checkout", domSelector: "#continue-checkout", bbox: [936, 716, 182, 44] },
            structuredRationale: "The requested address update is complete, so checkout can continue.",
            confidence: 0.84,
            stateAfter: "checkout_continue_ready",
          },
        ],
      },
      {
        traceId: "checkout-address-vision",
        agentId: "vision-gui-agent",
        agentKind: "vision_gui",
        modelId: "gui-vision-agent",
        taskId: "checkout-address",
        steps: [
          {
            stepIndex: 1,
            observationType: "screenshot",
            observationSummary: "Billing address card has a warning badge and a visually prominent edit button.",
            actionType: "click",
            target: { label: "Edit billing address", domSelector: "#edit-billing", bbox: [824, 468, 156, 38] },
            structuredRationale: "The warning badge makes the billing address area appear most in need of correction.",
            confidence: 0.79,
            stateAfter: "billing_form_open",
          },
          {
            stepIndex: 2,
            observationType: "screenshot",
            observationSummary: "Billing address form is open with address line field focused.",
            actionType: "type",
            target: { label: "Billing address line 1", domSelector: "#billing-line1", bbox: [420, 568, 420, 40] },
            inputText: "145 Market Street",
            structuredRationale: "The visible active form accepts the address change.",
            confidence: 0.76,
            stateAfter: "billing_address_edited",
          },
          {
            stepIndex: 3,
            observationType: "mixed",
            observationSummary: "Continue button is visible after editing the billing form.",
            actionType: "click",
            target: { label: "Continue checkout", domSelector: "#continue-checkout", bbox: [936, 716, 182, 44] },
            structuredRationale: "The page allows continuing after the edited address field.",
            confidence: 0.72,
            stateAfter: "checkout_continue_wrong_address",
          },
        ],
      },
    ],
  },
];

